# Generated by Django 2.2.4 on 2019-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('resume', models.FileField(upload_to='employee/resume/')),
                ('image', models.ImageField(null=True, upload_to='employee/images/')),
            ],
        ),
    ]
